#!/usr/bin/env node
// Regenerates ../oui.js from the official IEEE MA-L registry.
//
// The full registry is ~4 MB and ~37k entries; bundling all of it would be
// wasteful. This filters to a curated allowlist of consumer, IoT, and common
// home-network vendors and emits a compact lookup file. Locally-administered
// prefixes (Docker, QEMU, etc.) that are not in the IEEE registry are merged
// in as short startsWith prefixes.
//
// Usage: node scripts/build-oui.js
// Network: downloads https://standards-oui.ieee.org/oui/oui.csv

'use strict';
const https = require('https');
const fs = require('fs');
const path = require('path');

const SOURCE = 'https://standards-oui.ieee.org/oui/oui.csv';

// First matching rule wins, so put the more specific brand before its parent
// (Ring/eero/Blink before Amazon, Nest before Google).
const VENDOR_RULES = [
  [/^ring llc/i, 'Ring'],
  [/^eero\b/i, 'eero'],
  [/^blink by amazon|^immedia/i, 'Blink'],
  [/^amazon\b|^annapurna labs/i, 'Amazon'],
  [/^apple\b/i, 'Apple'],
  [/^nest labs|^google nest/i, 'Google Nest'],
  [/^google\b/i, 'Google'],
  [/\broku\b/i, 'Roku'],
  [/\bsonos\b/i, 'Sonos'],
  [/espressif/i, 'Espressif'],
  [/\btuya\b/i, 'Tuya'],
  [/sonoff|itead/i, 'Sonoff'],
  [/shelly|allterco/i, 'Shelly'],
  [/signify|philips lighting|philips hue|koninklijke philips/i, 'Philips/Signify'],
  [/\bwyze\b/i, 'Wyze'],
  [/ecobee/i, 'ecobee'],
  [/lutron/i, 'Lutron'],
  [/honeywell/i, 'Honeywell'],
  [/tp-link|tplink/i, 'TP-Link'],
  [/ubiquiti/i, 'Ubiquiti'],
  [/firewalla/i, 'Firewalla'],
  [/netgear/i, 'Netgear'],
  [/d-link|dlink/i, 'D-Link'],
  [/^asustek|^asus\b/i, 'ASUS'],
  [/^cisco\b|meraki/i, 'Cisco'],
  [/\baruba\b/i, 'Aruba'],
  [/samsung/i, 'Samsung'],
  [/lg electronics|lg innotek/i, 'LG'],
  [/^sony\b/i, 'Sony'],
  [/vizio/i, 'Vizio'],
  [/\btcl\b/i, 'TCL'],
  [/hisense/i, 'Hisense'],
  [/^microsoft\b/i, 'Microsoft'],
  [/^intel\b/i, 'Intel'],
  [/raspberry pi/i, 'Raspberry Pi'],
  [/synology/i, 'Synology'],
  [/\bqnap\b/i, 'QNAP'],
  [/\bnvidia\b/i, 'NVIDIA'],
  [/\bvmware\b/i, 'VMware'],
  [/belkin|wemo/i, 'Belkin'],
  [/irobot/i, 'iRobot'],
  [/withings/i, 'Withings'],
  [/^bose\b/i, 'Bose'],
  [/logitech/i, 'Logitech'],
  [/hikvision/i, 'Hikvision'],
  [/dahua|amcrest/i, 'Dahua/Amcrest'],
  [/reolink/i, 'Reolink'],
  [/^tesla\b/i, 'Tesla'],
  [/garmin/i, 'Garmin'],
  [/nintendo/i, 'Nintendo'],
  [/^valve corp/i, 'Valve'],
  [/\bxiaomi\b/i, 'Xiaomi'],
];

// Locally-administered or hypervisor MACs that are not in the IEEE registry.
// Matched by startsWith so both 4- and 6-octet prefixes work.
const PREFIXES = {
  '02:42': 'Docker',
  '52:54:00': 'QEMU/KVM',
  'fa:16:3e': 'OpenStack',
  '00:16:3e': 'Xen',
};

function parseCsvLine(line) {
  const out = [];
  let cur = '';
  let quoted = false;
  for (let i = 0; i < line.length; i++) {
    const c = line[i];
    if (quoted) {
      if (c === '"' && line[i + 1] === '"') { cur += '"'; i++; }
      else if (c === '"') quoted = false;
      else cur += c;
    } else if (c === '"') {
      quoted = true;
    } else if (c === ',') {
      out.push(cur); cur = '';
    } else {
      cur += c;
    }
  }
  out.push(cur);
  return out;
}

function classify(org) {
  for (const [re, name] of VENDOR_RULES) {
    if (re.test(org)) return name;
  }
  return null;
}

function download(url) {
  return new Promise((resolve, reject) => {
    https.get(url, res => {
      if (res.statusCode !== 200) { res.resume(); reject(new Error(`HTTP ${res.statusCode}`)); return; }
      let data = '';
      res.setEncoding('utf8');
      res.on('data', c => { data += c; });
      res.on('end', () => resolve(data));
    }).on('error', reject);
  });
}

async function main() {
  process.stderr.write('Downloading IEEE OUI registry...\n');
  const csv = await download(SOURCE);
  const lines = csv.split(/\r?\n/);
  const oui = {};
  let matched = 0;
  for (const line of lines) {
    if (!line || line.startsWith('Registry,')) continue;
    const f = parseCsvLine(line);
    const assignment = (f[1] || '').trim();
    const org = (f[2] || '').trim();
    if (!/^[0-9A-Fa-f]{6}$/.test(assignment)) continue;
    const vendor = classify(org);
    if (!vendor) continue;
    const key = assignment.toLowerCase().match(/.{2}/g).join(':');
    oui[key] = vendor;
    matched++;
  }

  const sortedKeys = Object.keys(oui).sort();
  const counts = {};
  for (const k of sortedKeys) counts[oui[k]] = (counts[oui[k]] || 0) + 1;

  const body = sortedKeys.map(k => `  '${k}': '${oui[k].replace(/'/g, "\\'")}',`).join('\n');
  const prefixBody = Object.entries(PREFIXES).map(([k, v]) => `  '${k}': '${v}',`).join('\n');

  const out = `// Generated by scripts/build-oui.js from the IEEE MA-L registry.
// Do not edit by hand. Re-run \`node scripts/build-oui.js\` to refresh.
// ${matched} curated vendor prefixes.

module.exports = {
  // 24-bit OUI (xx:xx:xx) -> vendor.
  oui: {
${body}
  },
  // Locally-administered / hypervisor prefixes, matched by startsWith.
  prefixes: {
${prefixBody}
  },
};
`;

  const dest = path.join(__dirname, '..', 'oui.js');
  fs.writeFileSync(dest, out);
  process.stderr.write(`Wrote ${dest} with ${matched} entries.\n`);
  process.stderr.write('By vendor: ' + Object.entries(counts).sort((a, b) => b[1] - a[1])
    .map(([v, c]) => `${v}=${c}`).join(', ') + '\n');
}

main().catch(e => { process.stderr.write('Failed: ' + e.message + '\n'); process.exit(1); });
